# Generated by Django 5.2.13 on 2026-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='jumlah',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_transaksi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
