# Generated by Django 5.2.13 on 2026-05-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_list_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_harga', to='inventory.list_stok')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga_suplier', to='inventory.suplier')),
            ],
        ),
    ]
