# Generated by Django 5.2.13 on 2026-05-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_hargastok'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaJual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaya_tenaga_kerja', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('biaya_listrik', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('keterangan_produk', models.TextField(blank=True, null=True)),
                ('harga_jual_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harga_jual_produk', to='inventory.list_stok')),
                ('harga_modal_bahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.hargastok')),
            ],
        ),
    ]
