# Generated by Django 5.2.13 on 2026-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_hargajual'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_stok',
            name='ukuran',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
