# Generated by Django 5.2.13 on 2026-05-10 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_list_stok_ukuran'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='list_stok',
            name='jenis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.jenisbarang'),
        ),
    ]
