# Generated by Django 5.2.13 on 2026-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_jenisbarang_list_stok_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_stok',
            name='nama_barang',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
