# Generated by Django 5.2.13 on 2026-05-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_list_stok_nama_barang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hargajual',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='hargajual',
            name='harga_modal_bahan',
        ),
        migrations.AddField(
            model_name='hargajual',
            name='nama_produk',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HargaJualBahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.list_stok')),
                ('harga_jual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_bahan', to='inventory.hargajual')),
                ('harga_stok_terpilih', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.hargastok')),
            ],
        ),
        migrations.AddField(
            model_name='hargajual',
            name='bahan_baku',
            field=models.ManyToManyField(related_name='produk_jual', through='inventory.HargaJualBahan', to='inventory.list_stok'),
        ),
    ]
