# Generated by Django 5.2.13 on 2026-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_hargajual_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hargajual',
            name='kode_produk',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
