# Generated by Django 5.2.13 on 2026-05-19 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_hargajual_kode_produk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArusStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('jenis_arus', models.CharField(choices=[('Pembelian', 'Pembelian (Stok Masuk)'), ('Pemakaian', 'Pemakaian (Stok Keluar)')], max_length=20)),
                ('qty_arus', models.IntegerField(default=0)),
                ('keterangan_arus', models.TextField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arus_stok', to='inventory.list_stok')),
            ],
        ),
    ]
