# Generated by Django 5.2.13 on 2026-06-18 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_arusstok'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order', 'Order (Antrean)'), ('desain', 'Proses Desain'), ('produksi', 'Proses Produksi/Cetak'), ('selesai', 'Selesai'), ('diambil', 'Sudah Diambil')], default='order', max_length=20, verbose_name='Status Order')),
                ('no_order', models.CharField(editable=False, max_length=50, unique=True, verbose_name='No Order')),
                ('tgl_order', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Order')),
                ('nama_order', models.CharField(max_length=255, verbose_name='Nama Order / Judul Project')),
                ('total_harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Harga')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'Data Order Utama',
            },
        ),
    ]
