# Generated by Django 5.2.13 on 2026-06-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_orderutama'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderutama',
            name='sisa_bayar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sisa Pembayaran'),
        ),
        migrations.AddField(
            model_name='orderutama',
            name='uang_muka',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Uang Muka (DP)'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pesanan', models.CharField(help_text='Nama cetakan/job, misal: Banner Warung Pecel', max_length=255)),
                ('nama_item', models.CharField(help_text='Nama produk dari tabel harga_jual, misal: BANNER OUTDOOR', max_length=255)),
                ('kode_item', models.CharField(blank=True, help_text='Kode barang/bahan, misal: 0500900001', max_length=50, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('panjang', models.DecimalField(decimal_places=2, default=1.0, help_text='Dalam meter', max_digits=10)),
                ('lebar', models.DecimalField(decimal_places=2, default=1.0, help_text='Dalam meter', max_digits=10)),
                ('harga_dasar', models.DecimalField(decimal_places=2, default=0.0, help_text='Harga modal/beli bahan', max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0.0, help_text='Harga jual per meter/satuan', max_digits=12)),
                ('jasa_desain', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('biaya_lain', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('keterangan', models.TextField(blank=True, help_text='Catatan finishing: mata ayam, lipat pres, dll', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.orderutama')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Detail',
            },
        ),
    ]
