# Generated by Django 5.2.13 on 2026-06-22 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_orderutama_sisa_bayar_orderutama_uang_muka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiutangPelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisa_piutang', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], default='Belum Lunas', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piutang', to='inventory.orderutama')),
            ],
        ),
        migrations.CreateModel(
            name='CicilanPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pembayaran', models.DateField(default=django.utils.timezone.now)),
                ('nominal_dicicil', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('piutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_cicilan', to='inventory.piutangpelanggan')),
            ],
        ),
    ]
