# Generated by Django 5.2.13 on 2026-06-22 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_piutangpelanggan_cicilanpiutang'),
    ]

    operations = [
        migrations.AddField(
            model_name='arusstok',
            name='harga_satuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='arusstok',
            name='suplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arus_suplier', to='inventory.suplier'),
        ),
    ]
