# Generated by Django 5.2.13 on 2026-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_arusstok_harga_satuan_arusstok_suplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='arusstok',
            name='pembayaran',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='arusstok',
            name='sisa_pembayaran',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='arusstok',
            name='tenggat_pembayaran',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hargastok',
            unique_together={('barang', 'suplier')},
        ),
    ]
