# Generated by Django 5.2.13 on 2026-06-23 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_arusstok_pembayaran_arusstok_sisa_pembayaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisa_hutang', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], default='Belum Lunas', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arus_stok', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hutang_detail', to='inventory.arusstok')),
            ],
        ),
    ]
