# Generated by Django 6.0.5 on 2026-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_arusstok_pembayaran_arusstok_sisa_pembayaran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(help_text='tanggal transaksi dibuat')),
                ('keterangan', models.TextField(blank=True, help_text='keterangan transaksi', null=True)),
                ('jenis', models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], help_text='jenis transaksi pemasukan atau pengeluaran', max_length=11)),
                ('nominal', models.DecimalField(decimal_places=2, help_text='nominal transaksi', max_digits=15)),
            ],
        ),
    ]
