# Generated by Django 5.2.13 on 2026-06-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_hutang'),
        ('inventory', '0018_transaksi'),
    ]

    operations = [
    ]
