# Generated by Django 5.2.13 on 2026-06-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_merge_0018_hutang_0018_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
