# Generated by Django 6.0.5 on 2026-06-29 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_kegiatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokOpname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('jenis', models.CharField(choices=[('Lebih', 'Lebih'), ('Kurang', 'Kurang'), ('Cocok', 'Cocok')], max_length=10)),
                ('qty_sistem', models.IntegerField(help_text='Jumlah stok di komputer saat opname dilakukan')),
                ('qty_gudang', models.IntegerField(help_text='Jumlah fisik barang yang dihitung nyata di gudang')),
                ('selisih', models.IntegerField(default=0, help_text='Hasil dari qty_gudang - qty_sistem')),
                ('stok_akhir', models.IntegerField(help_text='Stok final setelah disesuaikan')),
                ('keterangan', models.TextField(blank=True, help_text='Catatan tambahan alasan selisih', null=True)),
                ('barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stok_opname', to='inventory.list_stok')),
            ],
            options={
                'verbose_name_plural': 'Stok Opname',
            },
        ),
    ]
