# Generated by Django 5.2.13 on 2026-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_stokopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderutama',
            name='status',
            field=models.CharField(choices=[('order', 'Order'), ('proses', 'Proses'), ('selesai', 'Selesai')], default='order', max_length=20, verbose_name='Status Order'),
        ),
    ]
