# Generated by Django 6.0.5 on 2026-07-21 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_stokopname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('penerima', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
                ('tanggal_kirim', models.DateTimeField(default=django.utils.timezone.now)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengiriman', to='inventory.orderutama')),
            ],
            options={
                'verbose_name_plural': 'Data Pengiriman',
            },
        ),
        migrations.CreateModel(
            name='PengirimanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_kirim', models.IntegerField(default=1)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kirim', to='inventory.orderdetail')),
                ('pengiriman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='inventory.pengiriman')),
            ],
        ),
    ]
