# Generated by Django 5.2.13 on 2026-07-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_orderutama_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hutang',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
