# Generated by Django 5.2.13 on 2026-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_hutang_no_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hutang',
            name='no_invoice',
        ),
        migrations.AddField(
            model_name='arusstok',
            name='no_invoice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
