# Generated by Django 5.2.13 on 2026-07-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_hutang_no_invoice_arusstok_no_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderutama',
            name='alasan_hapus',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Dihapus / Dibatalkan'),
        ),
        migrations.AddField(
            model_name='orderutama',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dihapus'),
        ),
        migrations.AddField(
            model_name='orderutama',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
    ]
