# Generated by Django 5.2.13 on 2026-07-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_orderutama_alasan_hapus_orderutama_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hargajualbahan',
            name='produk_jadi_terpilih',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digunakan_sebagai_bahan', to='inventory.hargajual'),
        ),
        migrations.AlterField(
            model_name='hargajual',
            name='bahan_baku',
            field=models.ManyToManyField(related_name='produk_jual', through='inventory.HargaJualBahan', through_fields=('harga_jual', 'barang'), to='inventory.list_stok'),
        ),
        migrations.AlterField(
            model_name='hargajualbahan',
            name='barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.list_stok'),
        ),
        migrations.AlterField(
            model_name='hargajualbahan',
            name='harga_stok_terpilih',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.hargastok'),
        ),
    ]
