# Generated by Django 5.2.13 on 2026-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_hargajualbahan_produk_jadi_terpilih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderutama',
            name='kode_faktur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kode Faktur'),
        ),
        migrations.AddField(
            model_name='orderutama',
            name='tgl_pelunasan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Pelunasan'),
        ),
    ]
